[workspace]
resolver = "3"
members = ["openbrs_archv_cmprss", "openbrs_backup", "openbrs_compare", "openbrs_crypto", "openbrs_main", "openbrs_main_structs", "openbrs_stage"]

#[package]
#name = "OpenBRS"
#version = "0.1.0"
#edition = "2024"
