[package]
name = "openbrs_compare"
version = "0.1.0"
edition = "2024"

[dependencies]
openbrs_main_structs = { path = "../openbrs_main_structs" }
serde = { version = "1.0.228", features = ["derive"] } # For metadata file
serde_json = "1.0.145"
